# Use an official Node.js runtime as the base image
FROM python:3.12.3-alpine as build

# Set the working directory in the container to /app
WORKDIR /python

# Copy package.json and package-lock.json into the working directory
COPY ./backend/worker/requirements.txt ./

# Install the app dependencies inside the docker image
RUN pip install --no-cache-dir -r requirements.txt


# Define the command to run your app using CMD which defines your runtime
COPY ./backend/worker .

EXPOSE 3002

CMD [ "python", "./main.py"]