# FROM nginx:alpine
# Use an official OpenResty image as the base image
FROM openresty/openresty:alpine


# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Replace it with our custom Nginx configuration file
# COPY ./frontend/simple.conf /etc/nginx/conf.d/
COPY ./frontend/simple.conf /etc/nginx/conf.d/


# Create /var/log/nginx/ directory and symbolic links for access.log and error.log
RUN mkdir -p /var/log/nginx/ && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

# Copy static files to a different directory in the Nginx server
# COPY ./frontend/src /usr/share/nginx/html/src
# COPY ./frontend/index.html /usr/share/nginx/html
COPY ./frontend/src /usr/local/openresty/nginx/html/src
COPY ./frontend/index.html /usr/local/openresty/nginx/html


# Expose port 8080
EXPOSE 8080

# Start Nginx when the container has provisioned
# NOTE : 'nginx -t' to check syntax error before deploying!
# CMD ["nginx", "-g", "daemon off;"]
# CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]
CMD ["openresty", "-g", "daemon off;"]

