# Use an official Node.js runtime as the base image
FROM FROM nginx:alpine

# Set the working directory in the container to /app
# WORKDIR 

# Remove the default Nginx configuration file
# RUN rm /etc/nginx/conf.d/default.conf

# Replace it with our custom Nginx configuration file
# COPY frontend/nginx.conf /etc/nginx/conf.d/


# Copy static files to a different directory in the Nginx server
COPY ./frontend/src /usr/share/nginx/html
COPY ./frontend/index.html /usr/share/nginx/html


# Expose port 80
EXPOSE 80

# Start Nginx when the container has provisioned
CMD ["nginx", "-g", "daemon off;"]
