# Use an official Node.js runtime as the base image
FROM node:20.12.2-alpine as build

# Set the working directory in the container to /app
WORKDIR /nodejs

# Copy package.json and package-lock.json into the working directory
COPY ./frontend/package*.json ./

# Install the app dependencies inside the docker image
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY ./frontend/src ./src
COPY ./frontend/index.html ./


# Your package.json is configured to use port 80
EXPOSE 80

# Define the command to run your app using CMD which defines your runtime
CMD [ "npm", "run", "dev"]
